# https://docs.github.com/en/actions/learn-github-actions/environment-variables
name: Greeting on variable day

on:
  push:
    branches: [ docs ]
  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      # Environment variables. see https://docs.github.com/en/actions/learn-github-actions/environment-variables
      - name: "Say Hello Mona it's Monday"
        run: |
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
          env
        env:
          First_Name: Mona
      # install repo
      - name: checkout
        uses: actions/checkout@v3
      - run: npm install -g bats
      - name: Run build script
        run: |
          chmod +x ./.github/scripts/build.sh
          ./.github/scripts/build.sh
        shell: bash
      # Sharing data between jobs. see https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions#sharing-data-between-jobs
      - name: Sharing data between jobs
        shell: bash
        run: |
          expr 1 + 1 > output.log
          ls -l 
          cat output.log
          echo ${{ hashFiles('output.log') }}
      - name: Upload output file
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log
      - name: delete data between jobs
        if: ${{ always() }}
        run: |
          ls -l 
          cat output.log
          echo ${{ hashFiles('output.log') }}
          rm output.log
          ls -l 
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        if: ${{ always() }}
        with:
          name: output-log-file
      - name: check data between jobs
        if: ${{ always() }}
        run: |
          ls -l 
          cat output.log
          echo ${{ hashFiles('output.log') }}
      - name: a
        run: xxxxxxxxxxxxxx
      - name: b
        if: ${{ always() }}
        run: echo haha
      - name: c
        run: echo bb
      - name: job status check
        if: ${{ github.action_status == 'failure' }}
        run: echo qq

  # expression function json. see https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.job1.outputs.matrix)}}
    steps:
      - run: echo ${{needs.job1.outputs.matrix.include[0].project}}
